<a href="https://colab.research.google.com/github/RishikeshSahu06/ComputationalPhysics/blob/main/21174019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Computational Physics Lab 1 [04/01/2023]

This is a google colab, We will be using it for the computational physics laboratory. It has two types of blocks, code blocks for writing codes and text bolk like the present one. Here we can write comments/problems discussions etc.

We have two tutors:

Anu Sridevi. anubsreedevi.rs.phy20@itbhu.ac.in Sripan Mandal sripanmondal.rs.phy21@itbhu.ac.in

In [5]:
# This is how you put a comment in one line 
'''
Sometimes you need to comment out a part of the code 
or a several lines of elaborate comments. Then you do that way 
we are doing now. '''
5 + 3

8

In [6]:
5 - 3


2

In [7]:
5 / 3


1.6666666666666667

In [8]:
5 // 3

1

In [9]:
5 % 2

1

In [12]:
5 * 2

10

In [13]:
5 ** 3

125

In [14]:
pow(5,3)

125

In [15]:
# Lets print all together
# print integer %d
# print fraction %f

# print("Adding 5 with 3 gives me", 5+3)
print("Adding %d with %d gives me %d" %(5,3,5+3))
print(5-3)
print(5*3)

Adding 5 with 3 gives me 8
2
15


In [16]:
# Variables:   integers, fraction (floating point), strings
xx = 1
yy = 1.2
name = "Rishikesh"

print(xx + yy)   #coneverted to a string
print(name)

2.2
Rishikesh


In [17]:
# Using numpy scipy module

''' Dont use it this way
from numpy import *    #it will import everything in numpy module '''

import numpy as np
print(np.sin(0.1), np.sin(np.pi/2.))
print(np.cos(0.1), np.cos(np.pi/2.))    # will understand next week y its not giving actual zero
print(np.tan(0.1), np.tan(np.pi/2.))
print(np.arcsin(1.0), np.arctan(1.0), np.arccos(1.0))    # for inverse functions

0.09983341664682815 1.0
0.9950041652780258 6.123233995736766e-17
0.10033467208545055 1.633123935319537e+16
1.5707963267948966 0.7853981633974483 0.0


In [18]:
# Our First program

'''
Take two numbers in input and calculate the following:
sin(num 1) + cos (num2) and print the addition.

Pseudo code:
1. Input the first number
2. Input the second number
3. Do the operation
4. Print the output
'''
import numpy as np

print ("This program does an operation with two input numbers")
print ("Give a number: ")
num1 = float(input())
num2 = float(input("Input another number:"))

result = np.sin(num1) + np.cos(num2)
print("Result of operation is",result)

This program does an operation with two input numbers
Give a number: 
56
Input another number:56
Result of operation is 0.3316691056356723


Containers in Python

Properties:

ordered?
homogenous? mutable?

1. tuple: [ordered, heterogenous, non mutable]
2. list: [ordered, heterogenous, mutable]
3. array: [ordered, homogenous, mutable]

To get an element of an ordered container, one start by saying that the first element is element no 0.


In [19]:
# tuple

aa = (21174019, 'Rishikesh Sahu', (50.,20.,10.))  #tuple inside a tuple
print(aa[1],aa[0],aa[2])
print(aa[2][0])
# aa[2][0] = 1.       #it will give an error       as tuple is non mutable

Rishikesh Sahu 21174019 (50.0, 20.0, 10.0)
50.0


In [20]:
# list

aa = [21174019, 'Rishikesh Sahu', [50.,20.,10.]]
aa[2][0] = 20.    #list is mutable
print(aa[2])

[20.0, 20.0, 10.0]


In [21]:
# array

aa = np.array([1., 2.3, 4.5, 6.2, 7.])
bb = np.array([1., 2., 4.2, 6.2, 7.])
# print(aa + bb)
print(aa * bb)
print(np.dot(aa,bb))  #dot product of the vectors
# bb = aa.tolist() #converted to list
# bb.append(9.)

[ 1.    4.6  18.9  38.44 49.  ]
111.94


In [22]:
index = np.where(aa<3,)
aa[index]
print(aa[index],bb[index])
aa[np.where(aa<3)]
aa[aa<3]

[1.  2.3] [1. 2.]


array([1. , 2.3])

In [23]:
aa = np.array([[1,2,3],[5,6,7]])
print(aa)
aa[1,2]

[[1 2 3]
 [5 6 7]]


7

In [24]:
aa[1][2]

7

In [26]:
aa.shape

(2, 3)

In [55]:
# 1. Given input of n, find factorial n.

def factorial(n):
  if n == 0:
    return 1
  return n * factorial(n-1)

n = int(input("Enter n: "))
print(factorial(n))

Enter n: 0
1


In [54]:
# 2. Given inputs of n and p find n_C_p.
# n_C_p = n! / (p! * (n-p)!)

def combination(n, p):
    return factorial(n) / (factorial(p) * factorial(n-p))

n = int(input("Enter n: "))
p = int(input("Enter p: "))

print(combination(n, p))

Enter n: 0
Enter p: 0
1.0


In [52]:
# 3. Find all the numbers that are divisible by a number that you give in input.
 
def find_divisible(x, start, end):
  divisible_numbers = []
  for i in range(start, end+1):
    if i % x == 0:
      divisible_numbers.append(i)
  return divisible_numbers

n = int(input("Enter n: "))
start = int(input("Enter start: "))
end = int(input("Enter end: "))

print(find_divisible(n, start, end))

Enter n: 3
Enter start: 1
Enter end: 20
[3, 6, 9, 12, 15, 18]


In [56]:
# 1. Find all the pairs of numbers that add to 1000.

def find_pairs():
  pairs = []
  for x in range(1, 1000):
    pairs.append((x, 1000-x))
  return pairs

print(find_pairs())

[(1, 999), (2, 998), (3, 997), (4, 996), (5, 995), (6, 994), (7, 993), (8, 992), (9, 991), (10, 990), (11, 989), (12, 988), (13, 987), (14, 986), (15, 985), (16, 984), (17, 983), (18, 982), (19, 981), (20, 980), (21, 979), (22, 978), (23, 977), (24, 976), (25, 975), (26, 974), (27, 973), (28, 972), (29, 971), (30, 970), (31, 969), (32, 968), (33, 967), (34, 966), (35, 965), (36, 964), (37, 963), (38, 962), (39, 961), (40, 960), (41, 959), (42, 958), (43, 957), (44, 956), (45, 955), (46, 954), (47, 953), (48, 952), (49, 951), (50, 950), (51, 949), (52, 948), (53, 947), (54, 946), (55, 945), (56, 944), (57, 943), (58, 942), (59, 941), (60, 940), (61, 939), (62, 938), (63, 937), (64, 936), (65, 935), (66, 934), (67, 933), (68, 932), (69, 931), (70, 930), (71, 929), (72, 928), (73, 927), (74, 926), (75, 925), (76, 924), (77, 923), (78, 922), (79, 921), (80, 920), (81, 919), (82, 918), (83, 917), (84, 916), (85, 915), (86, 914), (87, 913), (88, 912), (89, 911), (90, 910), (91, 909), (92, 90

In [ ]:
# 2. Find all the triplets of numbers that add to 1000.

def find_triplets():
  for a in range(1, 1000):
    for b in range(1, 1000):
      c = 1000 - a - b
      if c>=0:
        print(f"Triplet found: {a}, {b}, {c}")

find_triplets()

In [75]:
# 3. Find all the prime numbers to 1000.

def find_primes(n):
  sieve = [True] * (n+1)
  sieve[0] = sieve[1] = False
  primes = []
  for i in range(2, n+1):
    if sieve[i]:
      primes.append(i)
      for j in range(i*i, n+1, i):
        sieve[j] = False
  return primes

print(find_primes(1000))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]
